### ISSUE TITLE
Current package name doesn't show on vscode search

### ISSUE THREAD

**Issue by renatoselenica** [leveluptuts/level-up-vscode-theme#2]
I realized this while trying to install the theme using the command `ext install theme-levelup`

The current name of the package is **theme-levelup** and with this name the theme does not show in the classical search on the visual studio interface.
![](https://i.imgur.com/wBDqspy.png)

This immediately changes when the name is changed as **theme-level-up**
![](https://i.imgur.com/Zd5crwz.png)

I prepared a pull request for this, but wanted to first of all check with you as this will require an update of the name of the package and update on the vscode marketplace. 

Edit: Sorry for the bad screenshots

**Comment by stolinski** [comment]
Merged. Thank you!
