### ISSUE TITLE
Terminal (ZSH) text is hardly readable

### ISSUE THREAD

**Issue by max-programming** [leveluptuts/level-up-vscode-theme#23]
The text in my terminal is hardly readable with the theme :(

![image](https://user-images.githubusercontent.com/51731966/105936004-f6ecfb00-6078-11eb-89e0-ab851cb14985.png)

![image](https://user-images.githubusercontent.com/51731966/105935978-eccafc80-6078-11eb-98f9-39fc4ba0dee9.png)

**Comment by stolinski** [comment]
This is an issue with whatever zsh theme you are using.
